FROM ubuntu:latest

ENV HOME=/root
RUN apt-get update
RUN apt-get install -y curl vim python php less sudo
RUN curl -# https://raw.githubusercontent.com/elifiner/linux-config/master/install.sh | bash

